// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssigmaapi/type/market.proto

package market

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Market struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Market) Reset()         { *m = Market{} }
func (m *Market) String() string { return proto.CompactTextString(m) }
func (*Market) ProtoMessage()    {}
func (*Market) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab1e020d5b8fd7f4, []int{0}
}

func (m *Market) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Market.Unmarshal(m, b)
}
func (m *Market) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Market.Marshal(b, m, deterministic)
}
func (m *Market) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Market.Merge(m, src)
}
func (m *Market) XXX_Size() int {
	return xxx_messageInfo_Market.Size(m)
}
func (m *Market) XXX_DiscardUnknown() {
	xxx_messageInfo_Market.DiscardUnknown(m)
}

var xxx_messageInfo_Market proto.InternalMessageInfo

func (m *Market) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Market) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func init() {
	proto.RegisterType((*Market)(nil), "ssigmaapi.type.Market")
}

func init() { proto.RegisterFile("ssigmaapi/type/market.proto", fileDescriptor_ab1e020d5b8fd7f4) }

var fileDescriptor_ab1e020d5b8fd7f4 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x2e, 0xce, 0x4c,
	0xcf, 0x4d, 0x4c, 0x2c, 0xc8, 0xd4, 0x2f, 0xa9, 0x2c, 0x48, 0xd5, 0xcf, 0x4d, 0x2c, 0xca, 0x4e,
	0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x83, 0x4b, 0xea, 0x81, 0x24, 0x95, 0x6c,
	0xb8, 0xd8, 0x7c, 0xc1, 0xf2, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0x95, 0xb9, 0x49, 0xf9, 0x39, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e, 0x90, 0x14, 0x17, 0x47, 0x6a, 0x45, 0x72, 0x46,
	0x62, 0x5e, 0x7a, 0xaa, 0x04, 0x13, 0x58, 0x06, 0xce, 0x77, 0x32, 0x89, 0x32, 0x4a, 0xcf, 0x2c,
	0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0x4e, 0xcc, 0x03, 0x1b, 0xae, 0x0f, 0xb7,
	0x23, 0x3d, 0x1f, 0xd9, 0x09, 0xd6, 0x10, 0x2a, 0x89, 0x0d, 0xec, 0x14, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x2a, 0x9c, 0x63, 0x20, 0xa9, 0x00, 0x00, 0x00,
}
