// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trade_model.proto

package sansigmaprotos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderPanel_OrderSide int32

const (
	OrderPanel_BUY  OrderPanel_OrderSide = 0
	OrderPanel_SELL OrderPanel_OrderSide = 1
)

var OrderPanel_OrderSide_name = map[int32]string{
	0: "BUY",
	1: "SELL",
}

var OrderPanel_OrderSide_value = map[string]int32{
	"BUY":  0,
	"SELL": 1,
}

func (x OrderPanel_OrderSide) String() string {
	return proto.EnumName(OrderPanel_OrderSide_name, int32(x))
}

func (OrderPanel_OrderSide) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{4, 0}
}

type Arbitrage_ArbitrageType int32

const (
	Arbitrage_SIMPLE     Arbitrage_ArbitrageType = 0
	Arbitrage_TRIANGULAR Arbitrage_ArbitrageType = 1
	Arbitrage_CIRCLE     Arbitrage_ArbitrageType = 2
)

var Arbitrage_ArbitrageType_name = map[int32]string{
	0: "SIMPLE",
	1: "TRIANGULAR",
	2: "CIRCLE",
}

var Arbitrage_ArbitrageType_value = map[string]int32{
	"SIMPLE":     0,
	"TRIANGULAR": 1,
	"CIRCLE":     2,
}

func (x Arbitrage_ArbitrageType) String() string {
	return proto.EnumName(Arbitrage_ArbitrageType_name, int32(x))
}

func (Arbitrage_ArbitrageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{5, 0}
}

type BidAsk struct {
	Price                float64  `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidAsk) Reset()         { *m = BidAsk{} }
func (m *BidAsk) String() string { return proto.CompactTextString(m) }
func (*BidAsk) ProtoMessage()    {}
func (*BidAsk) Descriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{0}
}

func (m *BidAsk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidAsk.Unmarshal(m, b)
}
func (m *BidAsk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidAsk.Marshal(b, m, deterministic)
}
func (m *BidAsk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidAsk.Merge(m, src)
}
func (m *BidAsk) XXX_Size() int {
	return xxx_messageInfo_BidAsk.Size(m)
}
func (m *BidAsk) XXX_DiscardUnknown() {
	xxx_messageInfo_BidAsk.DiscardUnknown(m)
}

var xxx_messageInfo_BidAsk proto.InternalMessageInfo

func (m *BidAsk) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BidAsk) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type OrderBook struct {
	Exchange             string    `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Base                 string    `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string    `protobuf:"bytes,3,opt,name=quote,proto3" json:"quote,omitempty"`
	Symbol               string    `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bids                 []*BidAsk `protobuf:"bytes,5,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks                 []*BidAsk `protobuf:"bytes,6,rep,name=asks,proto3" json:"asks,omitempty"`
	Timestamp            int64     `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OrderBook) Reset()         { *m = OrderBook{} }
func (m *OrderBook) String() string { return proto.CompactTextString(m) }
func (*OrderBook) ProtoMessage()    {}
func (*OrderBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{1}
}

func (m *OrderBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBook.Unmarshal(m, b)
}
func (m *OrderBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBook.Marshal(b, m, deterministic)
}
func (m *OrderBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBook.Merge(m, src)
}
func (m *OrderBook) XXX_Size() int {
	return xxx_messageInfo_OrderBook.Size(m)
}
func (m *OrderBook) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBook.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBook proto.InternalMessageInfo

func (m *OrderBook) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *OrderBook) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *OrderBook) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *OrderBook) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderBook) GetBids() []*BidAsk {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *OrderBook) GetAsks() []*BidAsk {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *OrderBook) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Spread struct {
	LongExchange         string   `protobuf:"bytes,1,opt,name=long_exchange,json=longExchange,proto3" json:"long_exchange,omitempty"`
	ShortExchange        string   `protobuf:"bytes,2,opt,name=short_exchange,json=shortExchange,proto3" json:"short_exchange,omitempty"`
	Base                 string   `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string   `protobuf:"bytes,4,opt,name=quote,proto3" json:"quote,omitempty"`
	ProfitRate           float64  `protobuf:"fixed64,5,opt,name=profit_rate,json=profitRate,proto3" json:"profit_rate,omitempty"`
	Profit               float64  `protobuf:"fixed64,6,opt,name=profit,proto3" json:"profit,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	InvestedCapital      float64  `protobuf:"fixed64,8,opt,name=invested_capital,json=investedCapital,proto3" json:"invested_capital,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Spread) Reset()         { *m = Spread{} }
func (m *Spread) String() string { return proto.CompactTextString(m) }
func (*Spread) ProtoMessage()    {}
func (*Spread) Descriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{2}
}

func (m *Spread) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Spread.Unmarshal(m, b)
}
func (m *Spread) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Spread.Marshal(b, m, deterministic)
}
func (m *Spread) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Spread.Merge(m, src)
}
func (m *Spread) XXX_Size() int {
	return xxx_messageInfo_Spread.Size(m)
}
func (m *Spread) XXX_DiscardUnknown() {
	xxx_messageInfo_Spread.DiscardUnknown(m)
}

var xxx_messageInfo_Spread proto.InternalMessageInfo

func (m *Spread) GetLongExchange() string {
	if m != nil {
		return m.LongExchange
	}
	return ""
}

func (m *Spread) GetShortExchange() string {
	if m != nil {
		return m.ShortExchange
	}
	return ""
}

func (m *Spread) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *Spread) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *Spread) GetProfitRate() float64 {
	if m != nil {
		return m.ProfitRate
	}
	return 0
}

func (m *Spread) GetProfit() float64 {
	if m != nil {
		return m.Profit
	}
	return 0
}

func (m *Spread) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Spread) GetInvestedCapital() float64 {
	if m != nil {
		return m.InvestedCapital
	}
	return 0
}

type Trade struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TradeId              string   `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Exchange             string   `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Base                 string   `protobuf:"bytes,4,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string   `protobuf:"bytes,5,opt,name=quote,proto3" json:"quote,omitempty"`
	Price                float64  `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Amount               float64  `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp            int64    `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Side                 string   `protobuf:"bytes,9,opt,name=side,proto3" json:"side,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{3}
}

func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Trade) GetTradeId() string {
	if m != nil {
		return m.TradeId
	}
	return ""
}

func (m *Trade) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Trade) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *Trade) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *Trade) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Trade) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Trade) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

type OrderPanel struct {
	Exchange             string               `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Base                 string               `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string               `protobuf:"bytes,3,opt,name=quote,proto3" json:"quote,omitempty"`
	Side                 OrderPanel_OrderSide `protobuf:"varint,4,opt,name=side,proto3,enum=sansigmaprotos.OrderPanel_OrderSide" json:"side,omitempty"`
	Price                float64              `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	DepthAmount          float64              `protobuf:"fixed64,6,opt,name=depth_amount,json=depthAmount,proto3" json:"depth_amount,omitempty"`
	OrderAmount          float64              `protobuf:"fixed64,7,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderPanel) Reset()         { *m = OrderPanel{} }
func (m *OrderPanel) String() string { return proto.CompactTextString(m) }
func (*OrderPanel) ProtoMessage()    {}
func (*OrderPanel) Descriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{4}
}

func (m *OrderPanel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderPanel.Unmarshal(m, b)
}
func (m *OrderPanel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderPanel.Marshal(b, m, deterministic)
}
func (m *OrderPanel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderPanel.Merge(m, src)
}
func (m *OrderPanel) XXX_Size() int {
	return xxx_messageInfo_OrderPanel.Size(m)
}
func (m *OrderPanel) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderPanel.DiscardUnknown(m)
}

var xxx_messageInfo_OrderPanel proto.InternalMessageInfo

func (m *OrderPanel) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *OrderPanel) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *OrderPanel) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *OrderPanel) GetSide() OrderPanel_OrderSide {
	if m != nil {
		return m.Side
	}
	return OrderPanel_BUY
}

func (m *OrderPanel) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderPanel) GetDepthAmount() float64 {
	if m != nil {
		return m.DepthAmount
	}
	return 0
}

func (m *OrderPanel) GetOrderAmount() float64 {
	if m != nil {
		return m.OrderAmount
	}
	return 0
}

type Arbitrage struct {
	Type                 Arbitrage_ArbitrageType `protobuf:"varint,1,opt,name=type,proto3,enum=sansigmaprotos.Arbitrage_ArbitrageType" json:"type,omitempty"`
	Orders               []*OrderPanel           `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	Profit               float64                 `protobuf:"fixed64,3,opt,name=profit,proto3" json:"profit,omitempty"`
	ProfitRate           float64                 `protobuf:"fixed64,4,opt,name=profit_rate,json=profitRate,proto3" json:"profit_rate,omitempty"`
	Investment           float64                 `protobuf:"fixed64,5,opt,name=investment,proto3" json:"investment,omitempty"`
	ProfitAsset          string                  `protobuf:"bytes,6,opt,name=profit_asset,json=profitAsset,proto3" json:"profit_asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Arbitrage) Reset()         { *m = Arbitrage{} }
func (m *Arbitrage) String() string { return proto.CompactTextString(m) }
func (*Arbitrage) ProtoMessage()    {}
func (*Arbitrage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{5}
}

func (m *Arbitrage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Arbitrage.Unmarshal(m, b)
}
func (m *Arbitrage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Arbitrage.Marshal(b, m, deterministic)
}
func (m *Arbitrage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Arbitrage.Merge(m, src)
}
func (m *Arbitrage) XXX_Size() int {
	return xxx_messageInfo_Arbitrage.Size(m)
}
func (m *Arbitrage) XXX_DiscardUnknown() {
	xxx_messageInfo_Arbitrage.DiscardUnknown(m)
}

var xxx_messageInfo_Arbitrage proto.InternalMessageInfo

func (m *Arbitrage) GetType() Arbitrage_ArbitrageType {
	if m != nil {
		return m.Type
	}
	return Arbitrage_SIMPLE
}

func (m *Arbitrage) GetOrders() []*OrderPanel {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *Arbitrage) GetProfit() float64 {
	if m != nil {
		return m.Profit
	}
	return 0
}

func (m *Arbitrage) GetProfitRate() float64 {
	if m != nil {
		return m.ProfitRate
	}
	return 0
}

func (m *Arbitrage) GetInvestment() float64 {
	if m != nil {
		return m.Investment
	}
	return 0
}

func (m *Arbitrage) GetProfitAsset() string {
	if m != nil {
		return m.ProfitAsset
	}
	return ""
}

type Market struct {
	Base                 string   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string   `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange             string   `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Market) Reset()         { *m = Market{} }
func (m *Market) String() string { return proto.CompactTextString(m) }
func (*Market) ProtoMessage()    {}
func (*Market) Descriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{6}
}

func (m *Market) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Market.Unmarshal(m, b)
}
func (m *Market) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Market.Marshal(b, m, deterministic)
}
func (m *Market) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Market.Merge(m, src)
}
func (m *Market) XXX_Size() int {
	return xxx_messageInfo_Market.Size(m)
}
func (m *Market) XXX_DiscardUnknown() {
	xxx_messageInfo_Market.DiscardUnknown(m)
}

var xxx_messageInfo_Market proto.InternalMessageInfo

func (m *Market) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *Market) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *Market) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Market) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

type OrderBooks struct {
	All                  []*OrderBook `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
	Timestamp            int64        `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *OrderBooks) Reset()         { *m = OrderBooks{} }
func (m *OrderBooks) String() string { return proto.CompactTextString(m) }
func (*OrderBooks) ProtoMessage()    {}
func (*OrderBooks) Descriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{7}
}

func (m *OrderBooks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBooks.Unmarshal(m, b)
}
func (m *OrderBooks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBooks.Marshal(b, m, deterministic)
}
func (m *OrderBooks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBooks.Merge(m, src)
}
func (m *OrderBooks) XXX_Size() int {
	return xxx_messageInfo_OrderBooks.Size(m)
}
func (m *OrderBooks) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBooks.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBooks proto.InternalMessageInfo

func (m *OrderBooks) GetAll() []*OrderBook {
	if m != nil {
		return m.All
	}
	return nil
}

func (m *OrderBooks) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type OrderBooksRequest struct {
	Base                 string   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string   `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	Exchanges            []string `protobuf:"bytes,3,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderBooksRequest) Reset()         { *m = OrderBooksRequest{} }
func (m *OrderBooksRequest) String() string { return proto.CompactTextString(m) }
func (*OrderBooksRequest) ProtoMessage()    {}
func (*OrderBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{8}
}

func (m *OrderBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBooksRequest.Unmarshal(m, b)
}
func (m *OrderBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBooksRequest.Marshal(b, m, deterministic)
}
func (m *OrderBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBooksRequest.Merge(m, src)
}
func (m *OrderBooksRequest) XXX_Size() int {
	return xxx_messageInfo_OrderBooksRequest.Size(m)
}
func (m *OrderBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBooksRequest proto.InternalMessageInfo

func (m *OrderBooksRequest) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *OrderBooksRequest) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *OrderBooksRequest) GetExchanges() []string {
	if m != nil {
		return m.Exchanges
	}
	return nil
}

type GetTradesRequest struct {
	// unit is seconds
	WindowingSize        int64     `protobuf:"varint,1,opt,name=windowing_size,json=windowingSize,proto3" json:"windowing_size,omitempty"`
	Markets              []*Market `protobuf:"bytes,2,rep,name=markets,proto3" json:"markets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetTradesRequest) Reset()         { *m = GetTradesRequest{} }
func (m *GetTradesRequest) String() string { return proto.CompactTextString(m) }
func (*GetTradesRequest) ProtoMessage()    {}
func (*GetTradesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{9}
}

func (m *GetTradesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTradesRequest.Unmarshal(m, b)
}
func (m *GetTradesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTradesRequest.Marshal(b, m, deterministic)
}
func (m *GetTradesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTradesRequest.Merge(m, src)
}
func (m *GetTradesRequest) XXX_Size() int {
	return xxx_messageInfo_GetTradesRequest.Size(m)
}
func (m *GetTradesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTradesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTradesRequest proto.InternalMessageInfo

func (m *GetTradesRequest) GetWindowingSize() int64 {
	if m != nil {
		return m.WindowingSize
	}
	return 0
}

func (m *GetTradesRequest) GetMarkets() []*Market {
	if m != nil {
		return m.Markets
	}
	return nil
}

type TradesWithMarket struct {
	Market               *Market  `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Trades               []*Trade `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradesWithMarket) Reset()         { *m = TradesWithMarket{} }
func (m *TradesWithMarket) String() string { return proto.CompactTextString(m) }
func (*TradesWithMarket) ProtoMessage()    {}
func (*TradesWithMarket) Descriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{10}
}

func (m *TradesWithMarket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradesWithMarket.Unmarshal(m, b)
}
func (m *TradesWithMarket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradesWithMarket.Marshal(b, m, deterministic)
}
func (m *TradesWithMarket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradesWithMarket.Merge(m, src)
}
func (m *TradesWithMarket) XXX_Size() int {
	return xxx_messageInfo_TradesWithMarket.Size(m)
}
func (m *TradesWithMarket) XXX_DiscardUnknown() {
	xxx_messageInfo_TradesWithMarket.DiscardUnknown(m)
}

var xxx_messageInfo_TradesWithMarket proto.InternalMessageInfo

func (m *TradesWithMarket) GetMarket() *Market {
	if m != nil {
		return m.Market
	}
	return nil
}

func (m *TradesWithMarket) GetTrades() []*Trade {
	if m != nil {
		return m.Trades
	}
	return nil
}

type GetTradesResponse struct {
	TradesWithMarket     []*TradesWithMarket `protobuf:"bytes,1,rep,name=trades_with_market,json=tradesWithMarket,proto3" json:"trades_with_market,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetTradesResponse) Reset()         { *m = GetTradesResponse{} }
func (m *GetTradesResponse) String() string { return proto.CompactTextString(m) }
func (*GetTradesResponse) ProtoMessage()    {}
func (*GetTradesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d21abb51656e18d4, []int{11}
}

func (m *GetTradesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTradesResponse.Unmarshal(m, b)
}
func (m *GetTradesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTradesResponse.Marshal(b, m, deterministic)
}
func (m *GetTradesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTradesResponse.Merge(m, src)
}
func (m *GetTradesResponse) XXX_Size() int {
	return xxx_messageInfo_GetTradesResponse.Size(m)
}
func (m *GetTradesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTradesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTradesResponse proto.InternalMessageInfo

func (m *GetTradesResponse) GetTradesWithMarket() []*TradesWithMarket {
	if m != nil {
		return m.TradesWithMarket
	}
	return nil
}

func init() {
	proto.RegisterEnum("sansigmaprotos.OrderPanel_OrderSide", OrderPanel_OrderSide_name, OrderPanel_OrderSide_value)
	proto.RegisterEnum("sansigmaprotos.Arbitrage_ArbitrageType", Arbitrage_ArbitrageType_name, Arbitrage_ArbitrageType_value)
	proto.RegisterType((*BidAsk)(nil), "sansigmaprotos.BidAsk")
	proto.RegisterType((*OrderBook)(nil), "sansigmaprotos.OrderBook")
	proto.RegisterType((*Spread)(nil), "sansigmaprotos.Spread")
	proto.RegisterType((*Trade)(nil), "sansigmaprotos.Trade")
	proto.RegisterType((*OrderPanel)(nil), "sansigmaprotos.OrderPanel")
	proto.RegisterType((*Arbitrage)(nil), "sansigmaprotos.Arbitrage")
	proto.RegisterType((*Market)(nil), "sansigmaprotos.Market")
	proto.RegisterType((*OrderBooks)(nil), "sansigmaprotos.OrderBooks")
	proto.RegisterType((*OrderBooksRequest)(nil), "sansigmaprotos.OrderBooksRequest")
	proto.RegisterType((*GetTradesRequest)(nil), "sansigmaprotos.GetTradesRequest")
	proto.RegisterType((*TradesWithMarket)(nil), "sansigmaprotos.TradesWithMarket")
	proto.RegisterType((*GetTradesResponse)(nil), "sansigmaprotos.GetTradesResponse")
}

func init() { proto.RegisterFile("trade_model.proto", fileDescriptor_d21abb51656e18d4) }

var fileDescriptor_d21abb51656e18d4 = []byte{
	// 906 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0xad, 0x63, 0xc7, 0x89, 0x6f, 0x9b, 0x90, 0x8e, 0x60, 0xe5, 0x8d, 0x56, 0x4b, 0x6a, 0x58,
	0x51, 0x40, 0x54, 0xab, 0x20, 0x01, 0x12, 0xe2, 0x21, 0xad, 0xa2, 0x52, 0x29, 0xfb, 0xa1, 0x49,
	0x57, 0x2b, 0xb4, 0x0f, 0xd6, 0xa4, 0x9e, 0x4d, 0x46, 0x89, 0x3f, 0xea, 0x99, 0x52, 0xba, 0x4f,
	0x3c, 0xf2, 0x77, 0xe0, 0x0f, 0xc1, 0x4f, 0x41, 0x33, 0xe3, 0xef, 0x26, 0x95, 0x90, 0x78, 0xf3,
	0x3d, 0x3e, 0xbe, 0x77, 0xce, 0x99, 0x33, 0x63, 0x38, 0x14, 0x29, 0x09, 0xa8, 0x1f, 0xc6, 0x01,
	0xdd, 0x9c, 0x24, 0x69, 0x2c, 0x62, 0xd4, 0xe7, 0x24, 0xe2, 0x6c, 0x19, 0x12, 0x55, 0x72, 0xef,
	0x3b, 0xb0, 0x4f, 0x59, 0x30, 0xe1, 0x6b, 0xf4, 0x31, 0xb4, 0x93, 0x94, 0x5d, 0x51, 0xd7, 0x18,
	0x19, 0xc7, 0x06, 0xd6, 0x05, 0x7a, 0x04, 0x36, 0x09, 0xe3, 0x9b, 0x48, 0xb8, 0x2d, 0x05, 0x67,
	0x95, 0xf7, 0xb7, 0x01, 0xce, 0xab, 0x34, 0xa0, 0xe9, 0x69, 0x1c, 0xaf, 0xd1, 0x10, 0xba, 0xf4,
	0xb7, 0xab, 0x15, 0x89, 0x96, 0xfa, 0x73, 0x07, 0x17, 0x35, 0x42, 0x60, 0x2d, 0x08, 0xa7, 0xea,
	0x7b, 0x07, 0xab, 0x67, 0x39, 0xeb, 0xfa, 0x26, 0x16, 0xd4, 0x35, 0x15, 0xa8, 0x0b, 0x39, 0x8b,
	0xdf, 0x85, 0x8b, 0x78, 0xe3, 0x5a, 0x0a, 0xce, 0x2a, 0xf4, 0x15, 0x58, 0x0b, 0x16, 0x70, 0xb7,
	0x3d, 0x32, 0x8f, 0xf7, 0xc7, 0x8f, 0x4e, 0xea, 0x12, 0x4e, 0xf4, 0xfa, 0xb1, 0xe2, 0x48, 0x2e,
	0xe1, 0x6b, 0xee, 0xda, 0x0f, 0x73, 0x25, 0x07, 0x3d, 0x01, 0x47, 0xb0, 0x90, 0x72, 0x41, 0xc2,
	0xc4, 0xed, 0x8c, 0x8c, 0x63, 0x13, 0x97, 0x80, 0xf7, 0x7b, 0x0b, 0xec, 0x79, 0x92, 0x52, 0x12,
	0xa0, 0xcf, 0xa0, 0xb7, 0x89, 0xa3, 0xa5, 0xdf, 0xd0, 0x78, 0x20, 0xc1, 0x69, 0xae, 0xf3, 0x19,
	0xf4, 0xf9, 0x2a, 0x4e, 0x45, 0xc9, 0xd2, 0x8a, 0x7b, 0x0a, 0x9d, 0x36, 0xed, 0x30, 0xb7, 0xd9,
	0x61, 0x55, 0xed, 0xf8, 0x14, 0xf6, 0x93, 0x34, 0x7e, 0xcf, 0x84, 0x9f, 0x12, 0x41, 0xdd, 0xb6,
	0xf2, 0x1f, 0x34, 0x84, 0x89, 0xf6, 0x4b, 0x57, 0xae, 0xad, 0xf7, 0x46, 0x57, 0x0f, 0xeb, 0x42,
	0x5f, 0xc2, 0x80, 0x45, 0xbf, 0x52, 0x2e, 0x68, 0xe0, 0x5f, 0x91, 0x84, 0x09, 0xb2, 0x71, 0xbb,
	0xea, 0xfb, 0x8f, 0x72, 0xfc, 0x4c, 0xc3, 0xde, 0x3f, 0x06, 0xb4, 0x2f, 0x65, 0x84, 0x2a, 0x5b,
	0x63, 0xd4, 0xb6, 0xe6, 0x31, 0x74, 0x75, 0xc6, 0x58, 0x90, 0xc9, 0xed, 0xa8, 0xfa, 0x22, 0xa8,
	0x65, 0xc2, 0xdc, 0x91, 0x09, 0x6b, 0x9b, 0x09, 0xed, 0xaa, 0x09, 0x45, 0x2a, 0xed, 0xed, 0xa9,
	0xec, 0x54, 0x53, 0x59, 0x57, 0xde, 0x6d, 0x2a, 0x47, 0x60, 0x71, 0x16, 0x50, 0xd7, 0xd1, 0x53,
	0xe5, 0xb3, 0xf7, 0x47, 0x0b, 0x40, 0xe5, 0xf8, 0x35, 0x89, 0xe8, 0xe6, 0x7f, 0x0a, 0xf2, 0x0f,
	0xd9, 0x20, 0x29, 0xaf, 0x3f, 0xfe, 0xbc, 0x19, 0xc2, 0x72, 0x9e, 0x7e, 0x9c, 0xb3, 0x80, 0xea,
	0xe5, 0x94, 0x72, 0xdb, 0x55, 0xb9, 0x47, 0x70, 0x10, 0xd0, 0x44, 0xac, 0xfc, 0x4c, 0xb4, 0xf6,
	0x62, 0x5f, 0x61, 0x13, 0xad, 0xfc, 0x08, 0x0e, 0x62, 0xd9, 0xcb, 0xaf, 0xf9, 0xb2, 0xaf, 0x30,
	0x4d, 0xf1, 0x9e, 0x66, 0x27, 0x56, 0x8e, 0x43, 0x1d, 0x30, 0x4f, 0xdf, 0xfc, 0x32, 0xd8, 0x43,
	0x5d, 0xb0, 0xe6, 0xd3, 0xd9, 0x6c, 0x60, 0x78, 0x7f, 0xb6, 0xc0, 0x99, 0xa4, 0x0b, 0x26, 0x52,
	0xb2, 0xa4, 0xe8, 0x47, 0xb0, 0xc4, 0x5d, 0xa2, 0x5d, 0xe8, 0x8f, 0xbf, 0x68, 0x6a, 0x28, 0x88,
	0xe5, 0xd3, 0xe5, 0x5d, 0x42, 0xb1, 0xfa, 0x08, 0x8d, 0xc1, 0x56, 0x93, 0xb9, 0xdb, 0x52, 0xe7,
	0x70, 0xb8, 0xdb, 0x02, 0x9c, 0x31, 0x2b, 0x69, 0x36, 0x6b, 0x69, 0x6e, 0x1c, 0x03, 0xeb, 0xde,
	0x31, 0x78, 0x0a, 0xa0, 0x83, 0x1b, 0xd2, 0x48, 0xe4, 0xc7, 0xa4, 0x44, 0xa4, 0x35, 0x59, 0x03,
	0xc2, 0x39, 0xd5, 0xee, 0x39, 0x38, 0x6b, 0x3a, 0x91, 0x90, 0xf7, 0x3d, 0xf4, 0x6a, 0x32, 0x10,
	0x80, 0x3d, 0xbf, 0x78, 0xf1, 0x7a, 0x36, 0x1d, 0xec, 0xa1, 0x3e, 0xc0, 0x25, 0xbe, 0x98, 0xbc,
	0x3c, 0x7f, 0x33, 0x9b, 0xe0, 0x81, 0x21, 0xdf, 0x9d, 0x5d, 0xe0, 0xb3, 0xd9, 0x74, 0xd0, 0xf2,
	0xde, 0x83, 0xfd, 0x82, 0xa4, 0x6b, 0x2a, 0x8a, 0x74, 0x18, 0xdb, 0xd2, 0xd1, 0xda, 0x7e, 0xcd,
	0x99, 0xb5, 0xb3, 0x54, 0xcd, 0x9e, 0x55, 0xcf, 0x9e, 0xf7, 0x36, 0x4b, 0xa9, 0xbc, 0x6d, 0x39,
	0xfa, 0x1a, 0x4c, 0xb2, 0x91, 0x47, 0x51, 0x7a, 0xfb, 0x78, 0xab, 0xb7, 0x92, 0x88, 0x25, 0xab,
	0x7e, 0x26, 0x5a, 0xcd, 0x5b, 0xee, 0x1d, 0x1c, 0x96, 0x8d, 0x31, 0xbd, 0xbe, 0xa1, 0xfc, 0xbf,
	0x68, 0x79, 0x02, 0x4e, 0xbe, 0x46, 0xee, 0x9a, 0x23, 0xf3, 0xd8, 0xc1, 0x25, 0xe0, 0xad, 0x61,
	0x70, 0x4e, 0x85, 0xba, 0x41, 0x8a, 0xde, 0xcf, 0xa0, 0x7f, 0xcb, 0xa2, 0x20, 0xbe, 0x65, 0xd1,
	0xd2, 0xe7, 0xec, 0x83, 0x9e, 0x62, 0xe2, 0x5e, 0x81, 0xce, 0xd9, 0x07, 0x8a, 0x9e, 0x43, 0x27,
	0x54, 0xc6, 0xe6, 0x11, 0xba, 0x77, 0x95, 0x6b, 0xdf, 0x71, 0x4e, 0xf3, 0xae, 0x61, 0xa0, 0x27,
	0xbd, 0x65, 0x62, 0x95, 0x6d, 0xca, 0x09, 0xd8, 0xfa, 0xb5, 0x1a, 0xb2, 0xbb, 0x49, 0xc6, 0x42,
	0xdf, 0x80, 0xad, 0xae, 0xaf, 0x7c, 0xe8, 0x27, 0x4d, 0xbe, 0x9a, 0x80, 0x33, 0x92, 0x77, 0x05,
	0x87, 0x15, 0x7d, 0x3c, 0x89, 0x23, 0x4e, 0xd1, 0x4b, 0x40, 0xfa, 0xb5, 0x7f, 0xcb, 0xc4, 0xca,
	0x2f, 0xe6, 0xcb, 0x7e, 0xa3, 0xad, 0xfd, 0x2a, 0x2b, 0xc6, 0x03, 0xd1, 0x40, 0xc6, 0xef, 0x00,
	0x15, 0x3b, 0x34, 0x17, 0x29, 0x25, 0xe1, 0x24, 0x61, 0x68, 0x0a, 0x07, 0xe7, 0x54, 0x94, 0x7f,
	0xe0, 0x1d, 0xca, 0x86, 0xbb, 0xd3, 0xe1, 0xed, 0x3d, 0x37, 0xc6, 0xaf, 0xa0, 0xaf, 0x96, 0x50,
	0x36, 0xfe, 0x09, 0xba, 0xb9, 0xa6, 0x9d, 0x4d, 0xb7, 0xdb, 0xa2, 0x1a, 0xfe, 0x65, 0x80, 0xfd,
	0xf3, 0xcd, 0x42, 0x76, 0xc2, 0xd0, 0xab, 0x2e, 0x91, 0xa3, 0xa3, 0x9d, 0x6b, 0xc9, 0xd3, 0x31,
	0x1c, 0xee, 0xa6, 0xc8, 0xf6, 0xe8, 0x12, 0x9c, 0xc2, 0x71, 0x74, 0xcf, 0xcd, 0x66, 0xd8, 0x86,
	0x47, 0x0f, 0x30, 0xf4, 0x76, 0xc9, 0xae, 0x0b, 0x5b, 0xbd, 0xfd, 0xf6, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x95, 0x27, 0xe7, 0xd2, 0x30, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderBookStreamApiClient is the client API for OrderBookStreamApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderBookStreamApiClient interface {
	GetOrderBook(ctx context.Context, in *Market, opts ...grpc.CallOption) (OrderBookStreamApi_GetOrderBookClient, error)
}

type orderBookStreamApiClient struct {
	cc *grpc.ClientConn
}

func NewOrderBookStreamApiClient(cc *grpc.ClientConn) OrderBookStreamApiClient {
	return &orderBookStreamApiClient{cc}
}

func (c *orderBookStreamApiClient) GetOrderBook(ctx context.Context, in *Market, opts ...grpc.CallOption) (OrderBookStreamApi_GetOrderBookClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderBookStreamApi_serviceDesc.Streams[0], "/sansigmaprotos.OrderBookStreamApi/GetOrderBook", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderBookStreamApiGetOrderBookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrderBookStreamApi_GetOrderBookClient interface {
	Recv() (*OrderBook, error)
	grpc.ClientStream
}

type orderBookStreamApiGetOrderBookClient struct {
	grpc.ClientStream
}

func (x *orderBookStreamApiGetOrderBookClient) Recv() (*OrderBook, error) {
	m := new(OrderBook)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrderBookStreamApiServer is the server API for OrderBookStreamApi service.
type OrderBookStreamApiServer interface {
	GetOrderBook(*Market, OrderBookStreamApi_GetOrderBookServer) error
}

func RegisterOrderBookStreamApiServer(s *grpc.Server, srv OrderBookStreamApiServer) {
	s.RegisterService(&_OrderBookStreamApi_serviceDesc, srv)
}

func _OrderBookStreamApi_GetOrderBook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Market)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderBookStreamApiServer).GetOrderBook(m, &orderBookStreamApiGetOrderBookServer{stream})
}

type OrderBookStreamApi_GetOrderBookServer interface {
	Send(*OrderBook) error
	grpc.ServerStream
}

type orderBookStreamApiGetOrderBookServer struct {
	grpc.ServerStream
}

func (x *orderBookStreamApiGetOrderBookServer) Send(m *OrderBook) error {
	return x.ServerStream.SendMsg(m)
}

var _OrderBookStreamApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sansigmaprotos.OrderBookStreamApi",
	HandlerType: (*OrderBookStreamApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetOrderBook",
			Handler:       _OrderBookStreamApi_GetOrderBook_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trade_model.proto",
}

// TradeStreamApiClient is the client API for TradeStreamApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TradeStreamApiClient interface {
	GetTrade(ctx context.Context, in *Market, opts ...grpc.CallOption) (TradeStreamApi_GetTradeClient, error)
}

type tradeStreamApiClient struct {
	cc *grpc.ClientConn
}

func NewTradeStreamApiClient(cc *grpc.ClientConn) TradeStreamApiClient {
	return &tradeStreamApiClient{cc}
}

func (c *tradeStreamApiClient) GetTrade(ctx context.Context, in *Market, opts ...grpc.CallOption) (TradeStreamApi_GetTradeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TradeStreamApi_serviceDesc.Streams[0], "/sansigmaprotos.TradeStreamApi/GetTrade", opts...)
	if err != nil {
		return nil, err
	}
	x := &tradeStreamApiGetTradeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TradeStreamApi_GetTradeClient interface {
	Recv() (*Trade, error)
	grpc.ClientStream
}

type tradeStreamApiGetTradeClient struct {
	grpc.ClientStream
}

func (x *tradeStreamApiGetTradeClient) Recv() (*Trade, error) {
	m := new(Trade)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TradeStreamApiServer is the server API for TradeStreamApi service.
type TradeStreamApiServer interface {
	GetTrade(*Market, TradeStreamApi_GetTradeServer) error
}

func RegisterTradeStreamApiServer(s *grpc.Server, srv TradeStreamApiServer) {
	s.RegisterService(&_TradeStreamApi_serviceDesc, srv)
}

func _TradeStreamApi_GetTrade_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Market)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TradeStreamApiServer).GetTrade(m, &tradeStreamApiGetTradeServer{stream})
}

type TradeStreamApi_GetTradeServer interface {
	Send(*Trade) error
	grpc.ServerStream
}

type tradeStreamApiGetTradeServer struct {
	grpc.ServerStream
}

func (x *tradeStreamApiGetTradeServer) Send(m *Trade) error {
	return x.ServerStream.SendMsg(m)
}

var _TradeStreamApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sansigmaprotos.TradeStreamApi",
	HandlerType: (*TradeStreamApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTrade",
			Handler:       _TradeStreamApi_GetTrade_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trade_model.proto",
}

// HubApiClient is the client API for HubApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HubApiClient interface {
	GetOrderBooks(ctx context.Context, in *OrderBooksRequest, opts ...grpc.CallOption) (HubApi_GetOrderBooksClient, error)
	GetTrades(ctx context.Context, in *GetTradesRequest, opts ...grpc.CallOption) (HubApi_GetTradesClient, error)
}

type hubApiClient struct {
	cc *grpc.ClientConn
}

func NewHubApiClient(cc *grpc.ClientConn) HubApiClient {
	return &hubApiClient{cc}
}

func (c *hubApiClient) GetOrderBooks(ctx context.Context, in *OrderBooksRequest, opts ...grpc.CallOption) (HubApi_GetOrderBooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HubApi_serviceDesc.Streams[0], "/sansigmaprotos.HubApi/GetOrderBooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &hubApiGetOrderBooksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HubApi_GetOrderBooksClient interface {
	Recv() (*OrderBooks, error)
	grpc.ClientStream
}

type hubApiGetOrderBooksClient struct {
	grpc.ClientStream
}

func (x *hubApiGetOrderBooksClient) Recv() (*OrderBooks, error) {
	m := new(OrderBooks)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hubApiClient) GetTrades(ctx context.Context, in *GetTradesRequest, opts ...grpc.CallOption) (HubApi_GetTradesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HubApi_serviceDesc.Streams[1], "/sansigmaprotos.HubApi/GetTrades", opts...)
	if err != nil {
		return nil, err
	}
	x := &hubApiGetTradesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HubApi_GetTradesClient interface {
	Recv() (*GetTradesResponse, error)
	grpc.ClientStream
}

type hubApiGetTradesClient struct {
	grpc.ClientStream
}

func (x *hubApiGetTradesClient) Recv() (*GetTradesResponse, error) {
	m := new(GetTradesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HubApiServer is the server API for HubApi service.
type HubApiServer interface {
	GetOrderBooks(*OrderBooksRequest, HubApi_GetOrderBooksServer) error
	GetTrades(*GetTradesRequest, HubApi_GetTradesServer) error
}

func RegisterHubApiServer(s *grpc.Server, srv HubApiServer) {
	s.RegisterService(&_HubApi_serviceDesc, srv)
}

func _HubApi_GetOrderBooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrderBooksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubApiServer).GetOrderBooks(m, &hubApiGetOrderBooksServer{stream})
}

type HubApi_GetOrderBooksServer interface {
	Send(*OrderBooks) error
	grpc.ServerStream
}

type hubApiGetOrderBooksServer struct {
	grpc.ServerStream
}

func (x *hubApiGetOrderBooksServer) Send(m *OrderBooks) error {
	return x.ServerStream.SendMsg(m)
}

func _HubApi_GetTrades_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTradesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubApiServer).GetTrades(m, &hubApiGetTradesServer{stream})
}

type HubApi_GetTradesServer interface {
	Send(*GetTradesResponse) error
	grpc.ServerStream
}

type hubApiGetTradesServer struct {
	grpc.ServerStream
}

func (x *hubApiGetTradesServer) Send(m *GetTradesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _HubApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sansigmaprotos.HubApi",
	HandlerType: (*HubApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetOrderBooks",
			Handler:       _HubApi_GetOrderBooks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTrades",
			Handler:       _HubApi_GetTrades_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trade_model.proto",
}
