# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import trade_model_pb2 as trade__model__pb2


class OrderBookStreamApiStub(object):
  """API from Hub server to Pashiri

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOrderBook = channel.unary_stream(
        '/sansigmaprotos.OrderBookStreamApi/GetOrderBook',
        request_serializer=trade__model__pb2.Market.SerializeToString,
        response_deserializer=trade__model__pb2.OrderBook.FromString,
        )


class OrderBookStreamApiServicer(object):
  """API from Hub server to Pashiri

  """

  def GetOrderBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OrderBookStreamApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOrderBook': grpc.unary_stream_rpc_method_handler(
          servicer.GetOrderBook,
          request_deserializer=trade__model__pb2.Market.FromString,
          response_serializer=trade__model__pb2.OrderBook.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sansigmaprotos.OrderBookStreamApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class TradeStreamApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTrade = channel.unary_stream(
        '/sansigmaprotos.TradeStreamApi/GetTrade',
        request_serializer=trade__model__pb2.Market.SerializeToString,
        response_deserializer=trade__model__pb2.Trade.FromString,
        )


class TradeStreamApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTrade(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TradeStreamApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTrade': grpc.unary_stream_rpc_method_handler(
          servicer.GetTrade,
          request_deserializer=trade__model__pb2.Market.FromString,
          response_serializer=trade__model__pb2.Trade.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sansigmaprotos.TradeStreamApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class HubApiStub(object):
  """API from End user to Hub server

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOrderBooks = channel.unary_stream(
        '/sansigmaprotos.HubApi/GetOrderBooks',
        request_serializer=trade__model__pb2.OrderBooksRequest.SerializeToString,
        response_deserializer=trade__model__pb2.OrderBooks.FromString,
        )
    self.GetTrades = channel.unary_stream(
        '/sansigmaprotos.HubApi/GetTrades',
        request_serializer=trade__model__pb2.GetTradesRequest.SerializeToString,
        response_deserializer=trade__model__pb2.GetTradesResponse.FromString,
        )


class HubApiServicer(object):
  """API from End user to Hub server

  """

  def GetOrderBooks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTrades(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HubApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOrderBooks': grpc.unary_stream_rpc_method_handler(
          servicer.GetOrderBooks,
          request_deserializer=trade__model__pb2.OrderBooksRequest.FromString,
          response_serializer=trade__model__pb2.OrderBooks.SerializeToString,
      ),
      'GetTrades': grpc.unary_stream_rpc_method_handler(
          servicer.GetTrades,
          request_deserializer=trade__model__pb2.GetTradesRequest.FromString,
          response_serializer=trade__model__pb2.GetTradesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sansigmaprotos.HubApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
