// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssigmaapi/pashirirest/v1/pashirirest.proto

package pashirirest

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	market "github.com/sansigma/ssigmaapigo/type/market"
	orderbook "github.com/sansigma/ssigmaapigo/type/orderbook"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("ssigmaapi/pashirirest/v1/pashirirest.proto", fileDescriptor_bd0c57650ee4c95a)
}

var fileDescriptor_bd0c57650ee4c95a = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2a, 0x2e, 0xce, 0x4c,
	0xcf, 0x4d, 0x4c, 0x2c, 0xc8, 0xd4, 0x2f, 0x48, 0x2c, 0xce, 0xc8, 0x2c, 0xca, 0x2c, 0x4a, 0x2d,
	0x2e, 0xd1, 0x2f, 0x33, 0x44, 0xe6, 0xea, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x49, 0xc0, 0xd5,
	0xea, 0x21, 0x4b, 0x96, 0x19, 0x4a, 0x49, 0x23, 0x4c, 0x29, 0xa9, 0x2c, 0x48, 0xd5, 0xcf, 0x4d,
	0x2c, 0xca, 0x4e, 0x85, 0x6a, 0x93, 0x92, 0x43, 0x93, 0xcc, 0x2f, 0x4a, 0x49, 0x2d, 0x4a, 0xca,
	0xcf, 0xcf, 0x86, 0xc8, 0x1b, 0xc5, 0x72, 0x89, 0x04, 0x40, 0x8c, 0x0b, 0x4a, 0x2d, 0x2e, 0x09,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x0d, 0x33, 0x14, 0x72, 0xe5, 0xe2, 0x71, 0x4f, 0x2d, 0xf1,
	0x07, 0xa9, 0x76, 0xca, 0xcf, 0xcf, 0x16, 0x12, 0xd3, 0x43, 0xd8, 0x0f, 0x32, 0x48, 0xcf, 0x17,
	0x6c, 0x8b, 0x94, 0x24, 0xba, 0x38, 0x5c, 0x8b, 0x12, 0x83, 0x01, 0xa3, 0x93, 0x4d, 0x94, 0x55,
	0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x71, 0x62, 0x1e, 0x58, 0xb1,
	0x3e, 0x5c, 0x4f, 0x7a, 0x3e, 0x9a, 0xcf, 0xad, 0x91, 0xb8, 0x49, 0x6c, 0x60, 0x37, 0x1a, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x27, 0xb7, 0x53, 0x2d, 0x28, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PashiriRestServiceV1Client is the client API for PashiriRestServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PashiriRestServiceV1Client interface {
	GetOrderBook(ctx context.Context, in *market.Market, opts ...grpc.CallOption) (PashiriRestServiceV1_GetOrderBookClient, error)
}

type pashiriRestServiceV1Client struct {
	cc *grpc.ClientConn
}

func NewPashiriRestServiceV1Client(cc *grpc.ClientConn) PashiriRestServiceV1Client {
	return &pashiriRestServiceV1Client{cc}
}

func (c *pashiriRestServiceV1Client) GetOrderBook(ctx context.Context, in *market.Market, opts ...grpc.CallOption) (PashiriRestServiceV1_GetOrderBookClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PashiriRestServiceV1_serviceDesc.Streams[0], "/ssigmaapi.pashirirest.v1.PashiriRestServiceV1/GetOrderBook", opts...)
	if err != nil {
		return nil, err
	}
	x := &pashiriRestServiceV1GetOrderBookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PashiriRestServiceV1_GetOrderBookClient interface {
	Recv() (*orderbook.OrderBook, error)
	grpc.ClientStream
}

type pashiriRestServiceV1GetOrderBookClient struct {
	grpc.ClientStream
}

func (x *pashiriRestServiceV1GetOrderBookClient) Recv() (*orderbook.OrderBook, error) {
	m := new(orderbook.OrderBook)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PashiriRestServiceV1Server is the server API for PashiriRestServiceV1 service.
type PashiriRestServiceV1Server interface {
	GetOrderBook(*market.Market, PashiriRestServiceV1_GetOrderBookServer) error
}

func RegisterPashiriRestServiceV1Server(s *grpc.Server, srv PashiriRestServiceV1Server) {
	s.RegisterService(&_PashiriRestServiceV1_serviceDesc, srv)
}

func _PashiriRestServiceV1_GetOrderBook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(market.Market)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PashiriRestServiceV1Server).GetOrderBook(m, &pashiriRestServiceV1GetOrderBookServer{stream})
}

type PashiriRestServiceV1_GetOrderBookServer interface {
	Send(*orderbook.OrderBook) error
	grpc.ServerStream
}

type pashiriRestServiceV1GetOrderBookServer struct {
	grpc.ServerStream
}

func (x *pashiriRestServiceV1GetOrderBookServer) Send(m *orderbook.OrderBook) error {
	return x.ServerStream.SendMsg(m)
}

var _PashiriRestServiceV1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ssigmaapi.pashirirest.v1.PashiriRestServiceV1",
	HandlerType: (*PashiriRestServiceV1Server)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetOrderBook",
			Handler:       _PashiriRestServiceV1_GetOrderBook_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ssigmaapi/pashirirest/v1/pashirirest.proto",
}
