// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sansigmaprotos/type/orderbook.proto

package orderbook

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BidAsk struct {
	Price                float64  `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidAsk) Reset()         { *m = BidAsk{} }
func (m *BidAsk) String() string { return proto.CompactTextString(m) }
func (*BidAsk) ProtoMessage()    {}
func (*BidAsk) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ee8e9234f3501ea, []int{0}
}

func (m *BidAsk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidAsk.Unmarshal(m, b)
}
func (m *BidAsk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidAsk.Marshal(b, m, deterministic)
}
func (m *BidAsk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidAsk.Merge(m, src)
}
func (m *BidAsk) XXX_Size() int {
	return xxx_messageInfo_BidAsk.Size(m)
}
func (m *BidAsk) XXX_DiscardUnknown() {
	xxx_messageInfo_BidAsk.DiscardUnknown(m)
}

var xxx_messageInfo_BidAsk proto.InternalMessageInfo

func (m *BidAsk) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BidAsk) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type OrderBook struct {
	Exchange             string    `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Base                 string    `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	Quote                string    `protobuf:"bytes,3,opt,name=quote,proto3" json:"quote,omitempty"`
	Symbol               string    `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bids                 []*BidAsk `protobuf:"bytes,5,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks                 []*BidAsk `protobuf:"bytes,6,rep,name=asks,proto3" json:"asks,omitempty"`
	Timestamp            int64     `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OrderBook) Reset()         { *m = OrderBook{} }
func (m *OrderBook) String() string { return proto.CompactTextString(m) }
func (*OrderBook) ProtoMessage()    {}
func (*OrderBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ee8e9234f3501ea, []int{1}
}

func (m *OrderBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBook.Unmarshal(m, b)
}
func (m *OrderBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBook.Marshal(b, m, deterministic)
}
func (m *OrderBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBook.Merge(m, src)
}
func (m *OrderBook) XXX_Size() int {
	return xxx_messageInfo_OrderBook.Size(m)
}
func (m *OrderBook) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBook.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBook proto.InternalMessageInfo

func (m *OrderBook) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *OrderBook) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *OrderBook) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *OrderBook) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OrderBook) GetBids() []*BidAsk {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *OrderBook) GetAsks() []*BidAsk {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *OrderBook) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*BidAsk)(nil), "ssigma.type.BidAsk")
	proto.RegisterType((*OrderBook)(nil), "ssigma.type.OrderBook")
}

func init() {
	proto.RegisterFile("sansigmaprotos/type/orderbook.proto", fileDescriptor_9ee8e9234f3501ea)
}

var fileDescriptor_9ee8e9234f3501ea = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4e, 0xf3, 0x30,
	0x10, 0xc7, 0xe5, 0x2f, 0x69, 0x3e, 0x72, 0xdd, 0x0c, 0x42, 0x16, 0x62, 0x88, 0xca, 0xd0, 0xb0,
	0xa4, 0x12, 0x48, 0x2c, 0x4c, 0xe4, 0x05, 0x90, 0x3c, 0xb2, 0xd9, 0x8d, 0x55, 0xac, 0xe0, 0x5c,
	0xc8, 0xb9, 0x12, 0x7d, 0x54, 0xde, 0x06, 0xf9, 0x52, 0x15, 0xa6, 0x6e, 0xf7, 0xff, 0xf9, 0x77,
	0xbe, 0xd3, 0xc1, 0x1d, 0x99, 0x81, 0xfc, 0x2e, 0x98, 0x71, 0xc2, 0x88, 0xb4, 0x89, 0x87, 0xd1,
	0x6d, 0x70, 0xea, 0xdc, 0x64, 0x11, 0xfb, 0x86, 0xa9, 0x5c, 0x12, 0x2b, 0x4d, 0x7a, 0x5c, 0x3d,
	0x41, 0xd1, 0xfa, 0xee, 0x85, 0x7a, 0x79, 0x05, 0x8b, 0x71, 0xf2, 0x5b, 0xa7, 0x44, 0x25, 0x6a,
	0xa1, 0xe7, 0x20, 0xaf, 0xa1, 0x30, 0x01, 0xf7, 0x43, 0x54, 0xff, 0x18, 0x1f, 0xd3, 0xea, 0x5b,
	0x40, 0xf9, 0x9a, 0x3e, 0x6e, 0x11, 0x7b, 0x79, 0x03, 0x17, 0xee, 0x6b, 0xfb, 0x6e, 0x86, 0xdd,
	0xdc, 0x5e, 0xea, 0x53, 0x96, 0x12, 0x72, 0x6b, 0xc8, 0x71, 0x7f, 0xa9, 0xb9, 0x4e, 0xb3, 0x3e,
	0xf7, 0x18, 0x9d, 0xca, 0x18, 0xce, 0x21, 0xcd, 0xa2, 0x43, 0xb0, 0xf8, 0xa1, 0x72, 0xc6, 0xc7,
	0x24, 0xd7, 0x90, 0x5b, 0xdf, 0x91, 0x5a, 0x54, 0x59, 0xbd, 0x7c, 0xb8, 0x6c, 0xfe, 0xec, 0xdf,
	0xcc, 0xcb, 0x6b, 0x16, 0x92, 0x68, 0xa8, 0x27, 0x55, 0x9c, 0x11, 0x93, 0x20, 0x6f, 0xa1, 0x8c,
	0x3e, 0x38, 0x8a, 0x26, 0x8c, 0xea, 0x7f, 0x25, 0xea, 0x4c, 0xff, 0x82, 0xf6, 0xfe, 0x6d, 0x7d,
	0xf6, 0x8e, 0xcf, 0xa7, 0xca, 0x16, 0x2c, 0x3c, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xa2,
	0x0d, 0xa2, 0x79, 0x01, 0x00, 0x00,
}
